import {
  Briefcase,
  Building2,
  MapPin,
  Heart,
  Cake,
  Gamepad2,
  Dumbbell,
  Users,
  GraduationCap,
  Phone,
  CircleDot,
  Globe,
  Baby,
  Languages,
  PawPrint,
  UserPlus,
  Quote,
  Fingerprint,
  Gift,
} from 'lucide-react-native';
import { FactType } from '@/types';

export const factIcons: Record<FactType, typeof Briefcase> = {
  work: Briefcase,
  company: Building2,
  hobby: Gamepad2,
  sport: Dumbbell,
  relationship: Users,
  partner: Heart,
  location: MapPin,
  education: GraduationCap,
  birthday: Cake,
  contact: Phone,
  origin: Globe,
  children: Baby,
  language: Languages,
  pet: PawPrint,
  how_met: UserPlus,
  where_met: MapPin,
  shared_ref: Quote,
  trait: Fingerprint,
  gift_idea: Gift,
  gift_given: Gift,
  other: CircleDot,
};

export const factLabels: Record<FactType, string> = {
  work: 'Travail',
  company: 'Entreprise',
  hobby: 'Loisir',
  sport: 'Sport',
  relationship: 'Relation',
  partner: 'Conjoint',
  location: 'Lieu',
  education: 'Formation',
  birthday: 'Anniversaire',
  contact: 'Contact',
  origin: 'Origine',
  children: 'Enfants',
  language: 'Langue',
  pet: 'Animal',
  how_met: 'Comment connu',
  where_met: 'Lieu de rencontre',
  shared_ref: 'Référence commune',
  trait: 'Trait distinctif',
  gift_idea: 'Idée cadeau',
  gift_given: 'Cadeau offert',
  other: 'Autre',
};
